//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BadgeManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public System.Guid EmployeeGuid { get; set; }

        [Display(Name = "ID")]        
        public int EmployeeNumber { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Date of Hire")]
        [DataType(DataType.Date)]
        public System.DateTime HireDate { get; set; }

        [Display(Name = "Date of Termination")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> TerminationDate { get; set; }

        [Display(Name = "Type")]
        public string Type { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "Shift")]
        public string Shift { get; set; }

        [Display(Name = "Department")]
        public string Department { get; set; }

        [Display(Name = "Title")]
        public string Title { get; set; }
    }
}
